send_message:
  name: Send SMS
  description: Send an SMS message via GOSMS.RU service
  fields:
    message:
      name: Message
      description: Message text (1 to 300 characters)
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
          min: 1
          max: 300
    phone:
      name: Phone Number
      description: Recipient's phone number in international format
      required: true
      example: "+79123456789"
      selector:
        text:
          min: 10
          max: 15
    device_id:
      name: Device ID
      description: Device ID from GOSMS.RU panel (optional)
      required: false
      example: "12345678-1234-1234-1234-123456789012"
      selector:
        text: {} 