name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master
      - name: Validate with HACS manifest
        uses: home-assistant/actions/validate-hacs-manifest@master 